# Site settings
title: YTG Blog
SEOTitle: 农夫果园的博客 | YTG Blog
header-img: img/YTG_1.jpg
email: 1756284275@qq.com
description: "Every failure is leading towards success."
keyword: "YTG, YTG Blog, 农夫果园的博客, name-longming, 袁田果, iOS, Apple, iPhone"
url: "http://name-longming.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/name-longming/name-longming.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Water drop stone wear!"
sidebar-avatar: /img/YTG.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     7241559508/profile?topnav=1&wvr=6
zhihu_username:     nong-fu-guo-yuan-45
github_username:    name-longming
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username:longming

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: fe76269a20cdf7826372                            #生成的clientID
  clientSecret: 00fbf2f9a69ba6f4d33bea3da892d8e9486694d3    #生成的clientSecret
  repo: name-longming.github.io    #仓库名称
  owner: name-longming    #github用户名
  admin: name-longming
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: f90be56dfcc886e2c125ee97e0ab7e98

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: nameytg.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CSDN博客",
        href: "https://blog.csdn.net/name_longming"
    },{
        title: "Github",
        href: "https://github.com/name-longming"
    },{
        title: "码云Gitee",
        href: "https://gitee.com/yuan_tianguo/dashboard/projects"
    },{
        title: "Bilibili",
        href: "https://space.bilibili.com/180941836"
    },{
        title: "薛黑先生",
        href: "https://x1247897956.github.io/"
    }
]
